version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION1}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION2}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION3}
    networks:
      - reddit

volumes:
  post_db:

networks:
  frontend-network:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  backend-network:
    ipam:
      config:
        - subnet: 10.0.2.0/24
